# Logo
logo_image_source: /images/soccer-ball.png

sponsors: hello

# Header
menu:
  Anmeldung: /files/Anmeldung_Peacely-Cup_2019_Pdf.pdf
  Sponsorenbrief: /files/Sponsorenbrief 2019.pdf
  Geschichte: /geschichte
  Das OK: /das-ok

# Index Page
index_banner_text: Peacely-Cup
index_banner_text_secondary: Der Cup mit Herz
index_font_awesome_icon_css: fa fa-futbol-o


# Post
default_post_title: Untitled
default_post_icon: fa-futbol-o

# Archive Date Format
archive_date_format: MMM YYYY
archive_font_awesome_icon_css: fa-folder-open

# About Widget
about_widget_avatar_url: http://tachyons.io/img/avatar_1.jpg
about_widget_text: "My name is Jonathan Klughertz and this is my blog.<br>I am a full stack software engineer with a strong front-end focus.<br> I currently live and work in Singapore, hit me up if you are in the region."


# Comments.
comments:
  # Disqus comments
  disqus_shortname: 

# Google Analytics Tracking ID
google_analytics:

# Social Media Platforms
social_platforms:
  - url: https://www.facebook.com/peacely-cup
    fa_icon: fa-facebook

# Footer about
footer_about: '&copy; <a class="link white" href="mailto:kt@compile.ch">Khôi Tran</a>'
